global:
  resolve_timeout: 1m
route:
  receiver: 'default-receiver'
  group_by: [alertname]
  group_interval: 2m
  routes:
    - match:
        scale: up
      receiver: app_up
    - match:
        scale: down
      receiver: app_down
receivers:
  - name: 'default-receiver'
  - name: 'app_up'
    webhook_configs:
      - url: 'http://orbiter:8000/v1/orbiter/handle/autoswarm/orbiterDemo_app/up'
  - name: 'app_down'
    webhook_configs:
      - url: 'http://orbiter:8000/v1/orbiter/handle/autoswarm/orbiterDemo_app/down'